/*.$file${.\Core\Inc::SharedData.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: model.qm
* File:  ${.\Core\Inc::SharedData.h}
*
* This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QP-EVAL-201231
* Issued to   : Institution or an individual evaluating the QP frameworks
* Framework(s): qpc qpcpp qpn
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* https://www.state-machine.com/licensing/#RequestForm
*/
/*.$endhead${.\Core\Inc::SharedData.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef SHAREDDATA_H
#define SHAREDDATA_H

#include "qf_port.h"

#define BSP_TICKS_PER_SEC 1000

// Enum de sinais.
enum signals
{
    // Eventos que podem ser utilizados pelo mecanismo de publish-subscribe.
    // Todos devem ficar antes de MAX_PUB_SIG,
    PISCAR_LED_SIG = Q_USER_SIG,
    MAX_PUB_SIG,

    // Eventos do SMLed.
    TIMEOUT_SIG,

};

/*.$declare${Eventos::EvtPiscaLED} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${Eventos::EvtPiscaLED} .................................................*/
typedef struct {
/* protected: */
    QEvt super;

/* public: */
    uint8_t quantidade;
} EvtPiscaLED;
/*.$enddecl${Eventos::EvtPiscaLED} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif