/*.$file${.\Core\Inc::SMConsumer.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: model.qm
* File:  ${.\Core\Inc::SMConsumer.h}
*
* This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QP-EVAL-201231
* Issued to   : Institution or an individual evaluating the QP frameworks
* Framework(s): qpc qpcpp qpn
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* https://www.state-machine.com/licensing/#RequestForm
*/
/*.$endhead${.\Core\Inc::SMConsumer.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef SMCONSUMER_H
#define SMCONSUMER_H

#include "qf_port.h"
#include "SharedData.h"

/*.$declare${AOs::SMConsumer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SMConsumer} ......................................................*/
typedef struct {
/* protected: */
    QMActive super;
} SMConsumer;

/* protected: */
QState SMConsumer_initial(SMConsumer * const me, void const * const par);
QState SMConsumer_Consumindo  (SMConsumer * const me, QEvt const * const e);
QState SMConsumer_Consumindo_e(SMConsumer * const me);
extern QMState const SMConsumer_Consumindo_s;
/*.$enddecl${AOs::SMConsumer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

void SMConsumer_ctor(void);

extern QMActive * const AO_SMConsumer;

#endif