/*.$file${.\Core\Src::SMConsumer.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: model.qm
* File:  ${.\Core\Src::SMConsumer.c}
*
* This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QP-EVAL-201231
* Issued to   : Institution or an individual evaluating the QP frameworks
* Framework(s): qpc qpcpp qpn
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* https://www.state-machine.com/licensing/#RequestForm
*/
/*.$endhead${.\Core\Src::SMConsumer.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "SMConsumer.h"
#include "SMConsumerActions.h"
#include "SharedData.h"

static SMConsumer l_consumer; /* the sole instance of the SMConsumer active object */

/* Public-scope objects
----------------------------------------------------*/
QMActive * const AO_SMConsumer = (QMActive *)&l_consumer; /*

opaque pointer */
void SMConsumer_ctor(void)
{
    SMConsumer *me = &l_consumer;

    // Construtor. Inicializa e coloca no estado inicial.
    QMActive_ctor(&me->super, Q_STATE_CAST(&SMConsumer_initial));
}

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 680U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.8.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::SMConsumer} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SMConsumer} ......................................................*/
/*.${AOs::SMConsumer::SM} ..................................................*/
QState SMConsumer_initial(SMConsumer * const me, void const * const par) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SMConsumer_Consumindo_s, /* target state */
        {
            Q_ACTION_CAST(&SMConsumer_Consumindo_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*.${AOs::SMConsumer::SM::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*.${AOs::SMConsumer::SM::Consumindo} ......................................*/
QMState const SMConsumer_Consumindo_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SMConsumer_Consumindo),
    Q_ACTION_CAST(&SMConsumer_Consumindo_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${AOs::SMConsumer::SM::Consumindo} */
QState SMConsumer_Consumindo_e(SMConsumer * const me) {
    QActive_subscribe((QActive *)me, PISCAR_LED_SIG);
    return QM_ENTRY(&SMConsumer_Consumindo_s);
}
/*.${AOs::SMConsumer::SM::Consumindo} */
QState SMConsumer_Consumindo(SMConsumer * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::SMConsumer::SM::Consumindo::PISCAR_LED} */
        case PISCAR_LED_SIG: {
            ToggleLED(Q_EVT_CAST(EvtPiscaLED)->quantidade);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.$enddef${AOs::SMConsumer} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
