/*.$file${.\Core\Src::SMLed.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: model.qm
* File:  ${.\Core\Src::SMLed.c}
*
* This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QP-EVAL-201231
* Issued to   : Institution or an individual evaluating the QP frameworks
* Framework(s): qpc qpcpp qpn
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* https://www.state-machine.com/licensing/#RequestForm
*/
/*.$endhead${.\Core\Src::SMLed.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "SMLed.h"
#include "SMLedActions.h"
#include "SharedData.h"

static SMLed l_led; /* the sole instance of the SMLed active object */

/* Public-scope objects
----------------------------------------------------*/
QMActive * const AO_SMLed = (QMActive *)&l_led; /* opaque pointer */

void SMLed_ctor(void)
{
    SMLed *me = &l_led;

    // Construtor. Inicializa e coloca no estado inicial.
    QMActive_ctor(&me->super, Q_STATE_CAST(&SMLed_initial));
    QTimeEvt_ctorX(&me->timer, (QActive *) &me->super, TIMEOUT_SIG, 0U);
}

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 680U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.8.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::SMLed} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::SMLed} ...........................................................*/
/*.${AOs::SMLed::SM} .......................................................*/
QState SMLed_initial(SMLed * const me, void const * const par) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &SMLed_Desligado_s, /* target state */
        {
            Q_ACTION_CAST(&SMLed_Desligado_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*.${AOs::SMLed::SM::initial} */
    return QM_TRAN_INIT(&tatbl_);
}
/*.${AOs::SMLed::SM::Desligado} ............................................*/
QMState const SMLed_Desligado_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&SMLed_Desligado),
    Q_ACTION_CAST(&SMLed_Desligado_e),
    Q_ACTION_CAST(&SMLed_Desligado_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${AOs::SMLed::SM::Desligado} */
QState SMLed_Desligado_e(SMLed * const me) {
    QTimeEvt_armX(&me->timer, BSP_TICKS_PER_SEC * 3, BSP_TICKS_PER_SEC/10);
    return QM_ENTRY(&SMLed_Desligado_s);
}
/*.${AOs::SMLed::SM::Desligado} */
QState SMLed_Desligado_x(SMLed * const me) {
    QTimeEvt_disarm(&me->timer);
    return QM_EXIT(&SMLed_Desligado_s);
}
/*.${AOs::SMLed::SM::Desligado} */
QState SMLed_Desligado(SMLed * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::SMLed::SM::Desligado::TIMEOUT} */
        case TIMEOUT_SIG: {
            PublicarEvento();
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.$enddef${AOs::SMLed} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
